# Generated by Django 3.2.9 on 2021-11-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestinfo',
            name='contest_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contestinfo',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
