# Generated by Django 3.2.9 on 2021-11-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20211127_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestinfo',
            name='start_time',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('handle', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('solved_problems', models.ManyToManyField(related_name='solved_by', to='crawler.Question')),
            ],
        ),
    ]
